routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    return view('welcome');
});


Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {

    Route::get('/home', function () {
        return view('admin.index');
    })->name('admin.home');

    Route::resource('/category', 'CategoryController');
    Route::delete('/category', 'CategoryController@deleteAll')->name('category.deleteAll');

    Route::resource('/product', 'ProductController');
    Route::delete('/product', 'ProductController@deleteAll')->name('poduct.deleteAll');

    Route::resource('/vendor', 'VendorController');
    Route::delete('/vendor', 'VendorController@deleteAll')->name('vendor.deleteAll');

    Route::resource('/promotion', 'PromotionController');
    Route::delete('/promotion', 'PromotionController@deleteAll')->name('promotion.deleteAll');
    Route::get('searchPromotionCode','PromotionController@searchPromotionCode')->name("promotion.search");

    Route::resource('/order', 'OrderController');
    Route::delete('/order', 'OrderController@deleteAll')->name('order.deleteAll');
    Route::get('searchProducts', 'OrderController@searchProduct')->name('order.searchProduct');
    Route::get('searchCustomers', 'OrderController@searchCustomer')->name('order.searchCustomer');
    Route::get('fetchCustomerInfo', 'OrderController@fetchCustomerInfo')->name('order.fetchCustomerInfo');
});

Auth::routes(['verify' => true]);

// Route::get('/authentication','Authen@showRegisterForm')->name('register');
// Route::post('/authentication','Authen@register')->name('user.register');

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function () {
    Route::resource('/users', 'UsersController', ['except' => ['show', 'create', 'store']]);
});


Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Model\Category;
use App\Model\Product;
use App\Model\Vendor;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Intervention\Image\ImageManagerStatic as Image;

use Aws\Credentials\Credentials;
use Aws\S3\S3Client;


class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $products = Product::orderBy('id', 'desc')->paginate(20);
        return view("admin.product.index", ['products' => $products]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $categories = Category::all();
        $vendors = Vendor::all();
        return view('admin.product.create', ['categories' => $categories, 'vendors' => $vendors]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validated = $request->validate([
            'name' => 'required',
            'category' => 'required',
            'price' => 'required|numeric',
            'stock' => 'required|numeric',
            'vendor' => 'required'
        ], [
            'name.required' => 'Product name was empty',
            'category.required' => 'Category was empty',
            'price.required' => 'Price was empty',
            'price.numeric' => 'Price have to be number',
            'stock.required' => 'Quantity was empty',
            'stock.numeric' => 'Quantity have to be number',
            'vendor.required' => 'Vendor was empty',
        ]);



        $imageUrl = 'default.jpg';
        if ($request->hasFile('image')) {
            $file       = $request->file('image');
            $filename    = Str::slug($request->name) . '-' . time() . '.' . $file->getClientOriginalExtension();

            $img = Image::make($file);

            $img->resize(200, 200, function ($constraint) {
                $constraint->aspectRatio();
            });

            $img->text('CDIO4 e-commerce', 10, 10, function ($text) {
                $text->color('#db1c1c');
            });

            //detach method is the key! Hours to find it... :/
            $resource = $img->stream()->detach();
            Storage::disk('s3')->put('s3-images/' . $filename, $resource);
            $imageUrl = "https://laravel-shopping-app.s3.ap-southeast-1.amazonaws.com/s3-images/" . $filename;
        }

        $product = new Product();
        $product->name = $request->name;
        $product->description = $request->description;
        $product->slug = Str::slug($request->name);
        $product->price = $request->price;
        $product->stock = $request->stock;
        $product->status = $request->status == 'on' ? 1 : 0;
        $product->image = $imageUrl;
        $product->category_id = $request->category;
        $product->vendor_id = $request->vendor;

        $product->save();

        return redirect()->back()->with('success', 'Added Product Successfull');
    }



    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        //
        $vendors = Vendor::all();
        $categories = Category::all();
        return view('admin.product.edit', ['product' => $product, 'categories' => $categories, 'vendors' => $vendors]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        //
        $validated = $request->validate([
            'name' => 'required',
            'category' => 'required',
            'price' => 'required|numeric',
            'stock' => 'required|numeric',
        ], [
            'name.required' => 'Product name was empty',
            'category.required' => 'Category was empty',
            'price.required' => 'Price was empty',
            'price.numeric' => 'Price have to be number',
            'stock.required' => 'Quantity was empty',
            'stock.numeric' => 'Quantity have to be number'
        ]);


        $imageUrl = 'default.jpg';
        if ($request->hasFile('image')) {
            $file       = $request->file('image');
            $filename    = Str::slug($request->name) . '-' . time() . '.' . $file->getClientOriginalExtension();

            $img = Image::make($file);

            $img->resize(200, 200, function ($constraint) {
                $constraint->aspectRatio();
            });

            $img->text('CDIO4 e-commerce', 10, 10, function ($text) {
                $text->color('#db1c1c');
            });

            //detach method is the key! Hours to find it... :/
            $resource = $img->stream()->detach();
            Storage::disk('s3')->put('s3-images/' . $filename, $resource);
            $imageUrl = "https://laravel-shopping-app.s3.ap-southeast-1.amazonaws.com/s3-images/" . $filename;
        }

        $product->name = $request->name;
        $product->description = $request->description;
        $product->slug = Str::slug($request->name);
        $product->price = $request->price;
        $product->stock = $request->stock;
        $product->status = $request->status == 'on' ? 1 : 0;
        if ($imageUrl) {
            $product->image = $imageUrl;
        }
        $product->category_id = $request->category;
        $product->vendor_id = $request->vendor;
        $product->save();

        return redirect()->back()->with('success', 'Updated Successfull');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        //
        $errors = null;
        try {
            Product::find($product->id)->delete();
        } catch (\Throwable $th) {
            $errors = $th;
        }

        return response()->json(['state' => $errors]);
    }

    /**
     * Remove the ALl resource from checkbox.
     *
     * @param  \App\Model\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function deleteAll(Request $request)
    {
        //
        $ids = $request->ids;

        $errors = null;
        try {
            Product::whereIn('id', $ids)->delete();
        } catch (\Throwable $th) {
            $errors = $th;
        }

        return response()->json(['data' => $errors]);
    }
}

resources/views/admin/product/create.blade.php
@extends('admin.layouts.master')

@section('content')

<div class="content-wrapper">

    <section class="content">
        <div class="row">
          <div class="col-md-6">
            @if(session()->has('success'))
            <div class="alert alert-success" style="width:200ox;margin:auto">
                {{ session()->get('success') }}
            </div>
            @endif
            <div class="card card-primary mt-3">
              <div class="card-header">
                <h3 class="card-title">General</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i></button>
                </div>
              </div>
              <div class="card-body">

                  <form action="{{route('product.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label>Category</label>
                        <select name="category" class="form-control @error('category') is-invalid @enderror " style="width: 100%;" tabindex="-1" aria-hidden="true">
                            @foreach ($categories as $category)
                                <option value="{{$category->id}}" name="" >{{$category->name}}</option>
                            @endforeach

                        </select>
                        @error('category')
                        <span class="error invalid-feedback">{{$message}}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Vendor</label>
                        <select name="vendor" class="form-control @error('vendor') is-invalid @enderror " style="width: 100%;" tabindex="-1" aria-hidden="true">
                            @foreach ($vendors as $vendor)
                                <option value="{{$vendor->id}}" name="" >{{$vendor->name}}</option>
                            @endforeach

                        </select>
                        @error('vendor')
                        <span class="error invalid-feedback">{{$message}}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="inputName">product Name</label>
                        <input name="name" type="text" id="inputName" class="form-control @error('name') is-invalid @enderror ">
                        @error('name')
                        <span class="error invalid-feedback">{{$message}}</span>
                        @enderror
                    </div>

                      <div class="form-group">
                        <label for="inputDescription">product Description</label>
                        <textarea name="description" id="inputDescription" class="form-control" rows="4"></textarea>
                      </div>

                      <div class="row">
                        <div class="form-group col-6">
                            <label for="inputPrice">product Price</label>
                            <input name="price" type="text" id="inputPrice" class="form-control @error('price') is-invalid @enderror ">
                            @error('price')
                            <span class="error invalid-feedback">{{$message}}</span>
                            @enderror
                        </div>
                        <div class="form-group col-6">
                            <label for="inputStock">product Quantity</label>
                            <input name="stock" type="text" id="inputStock" class="form-control @error('stock') is-invalid @enderror ">
                            @error('stock')
                            <span class="error invalid-feedback">{{$message}}</span>
                            @enderror
                        </div>
                      </div>

                      <div class="form-group" id="uploadForm">
                          <input type="file" name="image" id="file" />
                      </div>
                      <div class="form-group">
                          <label for="productStatus">Show</label>
                          <input type="checkbox" name="status" id="productStatus" checked >
                      </div>
                      <div class="form-group">
                          <input type="submit" value="Create new Porject" class="btn btn-success float-right">
                      </div>
                  </form>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          {{-- col-6 --}}
      </section>

</div>
@endsection

resources/views/admin/product/edit.blade.php
@extends('admin.layouts.master')

@section('content')

<div class="content-wrapper">

    <section class="content">
        <div class="row">
          <div class="col-md-6">
            @if(session()->has('success'))
            <div class="alert alert-success" style="width:200ox;margin:auto">
                {{ session()->get('success') }}
            </div>
            @endif
            <div class="card card-primary mt-3">
              <div class="card-header">
                <h3 class="card-title">General</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i></button>
                </div>
              </div>
              <div class="card-body">

                  <form action="{{route('product.update',$product->id)}}" method="POST" enctype="multipart/form-data">
                    {{method_field('PUT')}}
                    @csrf
                    <div class="form-group">
                        <label>Category</label>
                        <select name="category" class="form-control @error('category') is-invalid @enderror " style="width: 100%;" tabindex="-1" aria-hidden="true">

                            @foreach ($categories as $category)
                                <option value="{{$category->id}}"
                                @if ($product->category_id == $category->id)
                                    selected
                                @endif
                                >
                                {{$category->name}}
                                </option>
                            @endforeach

                        </select>
                        @error('category')
                        <span class="error invalid-feedback">{{$message}}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Vendor</label>
                        <select name="vendor" class="form-control @error('vendor') is-invalid @enderror " style="width: 100%;" tabindex="-1" aria-hidden="true">

                            @foreach ($vendors as $vendor)
                                <option value="{{$vendor->id}}"
                                @if ($product->vendor_id == $vendor->id)
                                    selected
                                @endif
                                >
                                {{$vendor->name}}
                                </option>
                            @endforeach

                        </select>
                        @error('vendor')
                        <span class="error invalid-feedback">{{$message}}</span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="inputName">product Name</label>
                        <input value="{{$product->name}}" name="name" type="text" id="inputName" class="form-control @error('name') is-invalid @enderror ">
                        @error('name')
                        <span class="error invalid-feedback">{{$message}}</span>
                        @enderror
                    </div>

                      <div class="form-group">
                        <label for="inputDescription">product Description</label>
                        <textarea name="description" id="inputDescription" class="form-control" rows="4">
                            {{$product->description}}
                        </textarea>
                      </div>

                      <div class="row">
                        <div class="form-group col-6">
                            <label for="inputPrice">product Price</label>
                            <input value="{{$product->price}}" name="price" type="text" id="inputPrice" class="form-control @error('price') is-invalid @enderror ">
                            @error('price')
                            <span class="error invalid-feedback">{{$message}}</span>
                            @enderror
                        </div>
                        <div class="form-group col-6">
                            <label for="inputStock">product Quantity</label>
                            <input value="{{$product->stock}}" name="stock" type="text" id="inputStock" class="form-control @error('stock') is-invalid @enderror ">
                            @error('stock')
                            <span class="error invalid-feedback">{{$message}}</span>
                            @enderror
                        </div>
                      </div>

                      <div class="form-group" id="uploadForm">
                          <input type="file" name="image" id="file" />
                      </div>
                      <img name="image_prev" src="{{url('upload',$product->image)}}" alt="" >
                      <div class="form-group">
                          <label for="productStatus">Show</label>
                          <input type="checkbox" name="status" id="productStatus" checked >
                      </div>
                      <div class="form-group">
                          <input type="submit" value="Update" class="btn btn-success float-right">
                      </div>
                  </form>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          {{-- col-6 --}}
      </section>

</div>
@endsection

resources/views/admin/product/index.blade.php
@extends('admin.layouts.master')

@section('content')
<div class="content-wrapper">



    <section class="p-3">
            <div class="d-flex justify-content-end" style="width:100%">
                <div style="width:120px;margin-right:20px">
                    <select name="" id=""  class="btn btn-success"  style="width:100%;height:100%">
                        <option value="1">All data</option>
                        <option value="1">1</option>
                        <option value="1">1</option>

                    </select>
                </div>
                <div class="d-flex">
                        <input type="text" value="" placeholder="Search Email or Id" style="width:200px">
                        <button>Search</button>
                </div>
            </div>
    </section>
    <section>
        <div class="d-flex justify-content-between">
            <div style="margin-left:10px;display:flex;flex-direction: row;align-items: center">
                <div><input type="checkbox" name="checkAll" id="checkProduct-all"></div>
                <div style="margin-left:20px"><Button class="btn btn-danger" id="deleteProduct-checked">Delete</Button></div>
                <div style="margin-left:20px"><button class="btn btn-success">Refresh</button></div>
                <div style="margin-left:20px"><button>ID Desc</button></div>
                <div style="margin-left:20px"><button>Sort</button></div>
            </div>
            <div style="margin-right:20px">
                <a href="{{route('product.create')}}" class="btn btn-success">Add new</a>
            </div>
        </div>
    </section>

    <!-- /.box-header -->
    <section id="pjax-container" class="table-list">
    <div class="box-body table-responsive no-padding" >
        <table class="table table-hover">
        <thead>
           <tr>
               <th></th>
               <th>STT</th>
               <th>Name</th>
               <th>Image</th>
               <th>Stock</th>
               <th>Description</th>
               <th>Price</th>
               <th>Status</th>
               <th>Actions</th>
           </tr>
        </thead>
        <tbody>
            @foreach ($products as $key =>$product)
            <tr>
                <td><input value="{{$product->id}}" type="checkbox" name="product" id="product-{{$product->id}}"></td>
                <td>{{$key}}</td>
                <td>{{$product->name}}</td>
                <td><img src=@if(!$product->image){{ url('default.jpg') }}   @else {{ filter_var($product->image, FILTER_VALIDATE_URL)?$product->image: url('upload',$product->image) }} @endif  alt="" width="100px" height="100px" /></td>
                <td>{{$product->stock}}</td>
                <td>{{$product->description}}</td>
                <td>${{$product->price}}</td>
                <td>{{$product->status ==1?"show":"hide"}}</td>
                <td>
                        <a href="{{route('product.edit',$product->id)}}"><span title="Edit" type="button" class="btn btn-flat btn-primary"><i class="fa fa-edit"></i></span></a>&nbsp;

                        <button  data-id="{{$product->id}}" title="Delete" class="btn btn-flat btn-danger deleteProduct"><i class="fa fa-trash"></i></button></td>
                </td>
            </tr>

            @endforeach

        </tbody>
        </table>
    </div>
    <div style="display:flex;align-self: center;justify-content: center">
        {{$products->links()}}
    </div>
    </section>
    <!-- /.box-body -->
    </div>

</div>


@endsection