routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    return view('welcome');
});


Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {

    Route::get('/home', function () {
        return view('admin.index');
    })->name('admin.home');

    Route::resource('/category', 'CategoryController');
    Route::delete('/category', 'CategoryController@deleteAll')->name('category.deleteAll');

    Route::resource('/product', 'ProductController');
    Route::delete('/product', 'ProductController@deleteAll')->name('poduct.deleteAll');

    Route::resource('/vendor', 'VendorController');
    Route::delete('/vendor', 'VendorController@deleteAll')->name('vendor.deleteAll');

    Route::resource('/promotion', 'PromotionController');
    Route::delete('/promotion', 'PromotionController@deleteAll')->name('promotion.deleteAll');
    Route::get('searchPromotionCode','PromotionController@searchPromotionCode')->name("promotion.search");

    Route::resource('/order', 'OrderController');
    Route::delete('/order', 'OrderController@deleteAll')->name('order.deleteAll');
    Route::get('searchProducts', 'OrderController@searchProduct')->name('order.searchProduct');
    Route::get('searchCustomers', 'OrderController@searchCustomer')->name('order.searchCustomer');
    Route::get('fetchCustomerInfo', 'OrderController@fetchCustomerInfo')->name('order.fetchCustomerInfo');
});

Auth::routes(['verify' => true]);

// Route::get('/authentication','Authen@showRegisterForm')->name('register');
// Route::post('/authentication','Authen@register')->name('user.register');

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function () {
    Route::resource('/users', 'UsersController', ['except' => ['show', 'create', 'store']]);
});


Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

app/User.php
<?php

namespace App;

use App\Model\Order;
use App\Model\OrderAddress;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;


use App\Model\Role;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }

    public function hasAnyRoles($role)
    {
        if ($this->roles()->whereIn('name', $role)->first()) {
            return true;
        }
        return false;
    }
    public function hasRole($role)
    {
        if ($this->roles()->where('name', $role)->first()) {
            return true;
        }
        return false;
    }

    public function orders()
    {
        return $this->hasMany(Order::class);
    }

    public function order_address(){
        return $this->hasMany(OrderAddress::class);
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use App\Model\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class UsersController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $users = User::orderBy('id', 'desc')->paginate(20);
        return view('admin.users.index', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
        if (Gate::denies('edit-users')) {
            return redirect()->route('admin.users.index')->with("denied", "Denied to access this function!!");
        }

        $roles = Role::all();

        return view('admin.users.edit', ['roles' => $roles, 'user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {

        $user->roles()->sync($request->roles);
        $user->email = $request->email;
        $user->name = $request->name;
        $user->save();
        return redirect()->route('admin.users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
        if (Gate::denies('delete-users')) {
            return redirect()->route('admin.users.index')->with("denied", "Denied to access this function!!");
        }

        $user->roles()->detach();
        $user->delete();

        return redirect()->route('admin.users.index');
    }
}

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.master')

@section('content')

<div class="content-wrapper">

    <section class="content">
        <div class="row">
          <div class="col-md-6">
            @if(session()->has('success'))
            <div class="alert alert-success" style="width:200ox;margin:auto">
                {{ session()->get('success') }}
            </div>
            @endif
            <div class="card card-primary mt-3">
              <div class="card-header">
                <h3 class="card-title">General</h3>
                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i></button>
                </div>
              </div>
              <div class="card-body">

                  <form action="{{route('admin.users.update',$user->id)}}" method="POST" enctype="multipart/form-data">
                    {{method_field('PUT')}}
                    @csrf

                    <div class="form-group row">
                        <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail') }}</label>

                        <div class="col-md-6">
                            <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{$user->email }}">

                            @error('email')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                        <div class="col-md-6">
                            <input id="name" type="name" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $user->name }}" >

                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="roles[]" class="col-md-4 col-form-label text-md-right">{{ __('Roles') }}</label>

                        <div class="col-md-6">
                            @foreach ($roles as $key => $role)
                            <div>
                                <input class="" @if($user->roles->pluck('id')->contains($role->id)) checked @endif type="checkbox" value="{{$role->id}}" name="roles[]" id="userRole-{{$role->id}}" >
                                <label for="userRole-{{$role->id}}">{{$role->name}}</label>
                            </div>
                            @endforeach
                        </div>

                    </div>


                      <div class="form-group">
                          <input type="submit" value="Update" class="btn btn-success float-right">
                      </div>
                  </form>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          {{-- col-6 --}}
      </section>

</div>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.master')

@section('content')
<div class="content-wrapper">



    <section class="p-3">
            <div class="d-flex justify-content-end" style="width:100%">
                <div style="width:120px;margin-right:20px">
                    <select name="" id=""  class="btn btn-success"  style="width:100%;height:100%">
                        <option value="1">All data</option>
                        <option value="1">1</option>
                        <option value="1">1</option>

                    </select>
                </div>
                <div class="d-flex">
                        <input type="text" value="" placeholder="Search Email or Id" style="width:200px">
                        <button>Search</button>
                </div>
            </div>
    </section>
    <section>
        <div class="d-flex justify-content-between">
            <div style="margin-left:10px;display:flex;flex-direction: row;align-items: center">
                <div><input type="checkbox" name="checkAll" id="checkuser-all"></div>
                <div style="margin-left:20px"><Button class="btn btn-danger" id="deleteuser-checked">Delete</Button></div>
                <div style="margin-left:20px"><button class="btn btn-success">Refresh</button></div>
                <div style="margin-left:20px"><button>ID Desc</button></div>
                <div style="margin-left:20px"><button>Sort</button></div>
            </div>
            <div style="margin-right:20px">
                <a href="" class="btn btn-success">Add new</a>
            </div>
        </div>
    </section>

    <!-- /.box-header -->
    <section id="pjax-container" class="table-list">
    <div class="box-body table-responsive no-padding" >
        <table class="table table-hover">
        <thead>
           <tr>
               <th></th>
               <th>STT</th>
               <th>Name</th>
               <th>Image</th>
               <th>Email</th>
               <th>Role</th>
               <th>Actions</th>
           </tr>
        </thead>
        <tbody>
            @foreach ($users as $key =>$user)
            <tr>
                <td><input value="{{$user->id}}" type="checkbox" name="user" id="user-{{$user->id}}"></td>
                <td>{{$key}}</td>
                <td>{{$user->name}}</td>
                <td><img src=@if(!$user->image){{ url('default.jpg') }}   @else {{ filter_var($user->image, FILTER_VALIDATE_URL)?$user->image: url('upload',$user->image) }} @endif  alt="" width="100px" height="100px" /></td>
                <td>{{$user->email}}</td>
                <td>{{  implode(',',$user->roles()->get()->pluck('name')->toArray()) }}</td>
                <td>
                        @can('edit-users')
                        <a href="{{route('admin.users.edit',$user->id)}}"><span title="Edit" type="button" class="btn btn-flat btn-primary"><i class="fa fa-edit"></i></span></a>&nbsp;
                        @endcan

                        @can('delete-users')
                        <a href="#" onclick="document.getElementById('delete-user').submit()">
                            <span title="Edit" type="button" class="btn btn-flat btn-danger"><i class="fa fa-trash"></i></span>
                        </a>&nbsp;
                        <form action="{{route('admin.users.destroy',['user'=>$user->id])}}" method="POST" id="delete-user">
                            @csrf
                            @method('DELETE')
                        </form>
                        @endcan

                </td>
            </tr>

            @endforeach

        </tbody>
        </table>
    </div>
    <div style="display:flex;align-self: center;justify-content: center">
        {{$users->links()}}
    </div>
    </section>
    <!-- /.box-body -->
        <div class="get-session">
            @if(session()->has('denied'))
                <div id="denied">
                </div>
             @endif
        </div>
    </div>

</div>


@endsection