routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    return view('welcome');
});


Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {

    Route::get('/home', function () {
        return view('admin.index');
    })->name('admin.home');

    Route::resource('/category', 'CategoryController');
    Route::delete('/category', 'CategoryController@deleteAll')->name('category.deleteAll');

    Route::resource('/product', 'ProductController');
    Route::delete('/product', 'ProductController@deleteAll')->name('poduct.deleteAll');

    Route::resource('/vendor', 'VendorController');
    Route::delete('/vendor', 'VendorController@deleteAll')->name('vendor.deleteAll');

    Route::resource('/promotion', 'PromotionController');
    Route::delete('/promotion', 'PromotionController@deleteAll')->name('promotion.deleteAll');
    Route::get('searchPromotionCode','PromotionController@searchPromotionCode')->name("promotion.search");

    Route::resource('/order', 'OrderController');
    Route::delete('/order', 'OrderController@deleteAll')->name('order.deleteAll');
    Route::get('searchProducts', 'OrderController@searchProduct')->name('order.searchProduct');
    Route::get('searchCustomers', 'OrderController@searchCustomer')->name('order.searchCustomer');
    Route::get('fetchCustomerInfo', 'OrderController@fetchCustomerInfo')->name('order.fetchCustomerInfo');
});

Auth::routes(['verify' => true]);

// Route::get('/authentication','Authen@showRegisterForm')->name('register');
// Route::post('/authentication','Authen@register')->name('user.register');

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function () {
    Route::resource('/users', 'UsersController', ['except' => ['show', 'create', 'store']]);
});


Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Model\Order;
use App\Model\OrderAddress;
use App\Model\OrderDetail;
use App\Model\Product;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use SebastianBergmann\Environment\Console;
use Illuminate\Support\Carbon;


class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $orders = Order::orderBy('id', 'desc')->paginate(20);

        return view('admin.orders.index', ['orders' => $orders]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

        return view('admin.orders.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //




        $products = null;
        $customer = null;
        $address = null;
        $errors = null;
        $user_id =null;
        $discount = null;
        $payment = null;
        $getProducts = array();
        if ($request->ajax()) {
            if ($request->get('products')) {
                $data = $request->products;
                foreach ($data as $key => $value) {
                    array_push($getProducts, $value);
                }
            }

            try {

                $totalPrice = $request->totalPrice;
                $user_id = $request->customer['id']?$request->customer['id']:null;

                if(!$user_id){
                    $user_name = $request->customer['name'];
                    $user_email = $request->customer['email'];
                    $user_phone = $request->customer['phone'];
                    $user_pass = Hash::make("12345678");
                    $user_id = DB::table('users')->insertGetId(
                        array('name'=>$user_name,'email'=>$user_email,'password'=>$user_pass,'phone'=>$user_phone)
                    );
                }
                $product = null;
                $currentDateTime = Carbon::now('Asia/Ho_Chi_Minh');

                if($request->discount){
                    $discount = $request->discount;
                    $totalPrice = $totalPrice - $discount;
                }
                if($request->payment){
                    $payment = $request->payment;
                }
                $orderId = DB::table('orders')->insertGetId(
                    array('subtotal' => $totalPrice, 'user_id' => $user_id,'discount'=>$discount,'payment_method'=>$payment,'created_at'=>$currentDateTime,'updated_at'=>$currentDateTime)
                );
                $address = $request->address;
                $orderAddress = new OrderAddress();
                $orderAddress->order_id = $orderId;
                $orderAddress->user_id = $user_id;
                $orderAddress->province = $address['province'];
                $orderAddress->district = $address['district'];
                $orderAddress->subDistrict = $address['subDistrict'];
                $orderAddress->street = $address['street'];
                $orderAddress->address = $address['province'].'-'.$address['district'].'-'.$address['subDistrict'].'-'.$address['street'];
                $orderAddress->save();
                foreach ($getProducts as $key => $value) {
                    $orderDetail = new OrderDetail();
                    $orderDetail->quantity = $value['quantity'];
                    $orderDetail->product_id = $value['id'];
                    try {
                        $product =  Product::find($value['id']);
                        $product->stock = $product->stock - $value['quantity'];
                        $product->save();
                    } catch (\Throwable $th) {
                        throw $errors =  $th;
                    }

                    $orderDetail->order_id = $orderId;
                    $orderDetail->save();
                }

            } catch (\Throwable $th) {
                throw $errors =  $th;
            }
        }



        return response()->json(['data' => $errors]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        //
        return view('admin.orders.show', ['order' => $order]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        //
        $errors = null;
        try {
            Order::find($order->id)->delete();
        } catch (\Throwable $th) {
            $errors = $th;
        }

        return response()->json(['state' => $errors]);
    }
    /**
     * Remove the specified resource from storage.
     *
     */
    public function deleteAll(Request $request)
    {
        //
        $ids = $request->ids;

        $errors = null;
        try {
            Order::whereIn('id', $ids)->delete();
        } catch (\Throwable $th) {
            $errors = $th;
        }

        return response()->json(['data' => $errors]);
    }

    /**
     * Search product
     *

     */
    public function searchProduct(Request $request)
    {
        //
        $data = "";
        if ($request->ajax()) {
            if ($request->get('query')) {
                $query = $request->get('query');
                $data = Product::where('name', 'like', '%' . $query . '%')
                    ->orWhere('id', 'like', '%' . $query . '%')->get();
            }
        }

        return response()->json(['data' => $data]);
    }


    /**
     * Search Customer
     *

     */
    public function searchCustomer(Request $request)
    {
        //
        $data = "";
        if ($request->ajax()) {
            if ($request->get('query')) {
                $query = $request->get('query');
                $data = User::where('name', 'like', '%' . $query . '%')
                    ->orWhere('id', 'like', '%' . $query . '%')
                    ->orWhere('email', 'like', '%' . $query . '%')->get();
            }
        }

        return response()->json(['data' => $data]);
    }

    /**
     * Fetch Customer Infor
     *

     */
    public function fetchCustomerInfo(Request $request)
    {
        //
        $customer = "";
        $orderAddress = null;
        if ($request->ajax()) {
            if ($request->get('id')) {
                $customer = User::where('id', $request->id)->get();
                $orderAddress = User::find($request->id)->order_address()->first();
            }
        }

        return response()->json(['data' => $customer,'orderAddress'=>$orderAddress]);
    }
}

resources/views/admin/orders/edit.blade.php
@extends('admin.layouts.master')

@section('content')

<div class="content-wrapper">

    <section class="content">
        <div class="row">
          <div class="col-md-6">
            @if(session()->has('success'))
            <div class="alert alert-success" style="width:200ox;margin:auto">
                {{ session()->get('success') }}
            </div>
            @endif
            <div class="card card-primary mt-3">
              <div class="card-header">
                <h3 class="card-title">General</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i></button>
                </div>
              </div>
              <div class="card-body">

                  <form action="{{route('product.update',$product->id)}}" method="POST" enctype="multipart/form-data">
                    {{method_field('PUT')}}
                    @csrf
                    <div class="form-group">
                        <label>Category</label>
                        <select name="category" class="form-control @error('category') is-invalid @enderror " style="width: 100%;" tabindex="-1" aria-hidden="true">

                            @foreach ($categories as $category)
                                <option value="{{$category->id}}"
                                @if ($product->category_id == $category->id)
                                    selected
                                @endif
                                >
                                {{$category->name}}
                                </option>
                            @endforeach

                        </select>
                        @error('category')
                        <span class="error invalid-feedback">{{$message}}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Vendor</label>
                        <select name="vendor" class="form-control @error('vendor') is-invalid @enderror " style="width: 100%;" tabindex="-1" aria-hidden="true">

                            @foreach ($vendors as $vendor)
                                <option value="{{$vendor->id}}"
                                @if ($product->vendor_id == $vendor->id)
                                    selected
                                @endif
                                >
                                {{$vendor->name}}
                                </option>
                            @endforeach

                        </select>
                        @error('vendor')
                        <span class="error invalid-feedback">{{$message}}</span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="inputName">product Name</label>
                        <input value="{{$product->name}}" name="name" type="text" id="inputName" class="form-control @error('name') is-invalid @enderror ">
                        @error('name')
                        <span class="error invalid-feedback">{{$message}}</span>
                        @enderror
                    </div>

                      <div class="form-group">
                        <label for="inputDescription">product Description</label>
                        <textarea name="description" id="inputDescription" class="form-control" rows="4">
                            {{$product->description}}
                        </textarea>
                      </div>

                      <div class="row">
                        <div class="form-group col-6">
                            <label for="inputPrice">product Price</label>
                            <input value="{{$product->price}}" name="price" type="text" id="inputPrice" class="form-control @error('price') is-invalid @enderror ">
                            @error('price')
                            <span class="error invalid-feedback">{{$message}}</span>
                            @enderror
                        </div>
                        <div class="form-group col-6">
                            <label for="inputStock">product Quantity</label>
                            <input value="{{$product->stock}}" name="stock" type="text" id="inputStock" class="form-control @error('stock') is-invalid @enderror ">
                            @error('stock')
                            <span class="error invalid-feedback">{{$message}}</span>
                            @enderror
                        </div>
                      </div>

                      <div class="form-group" id="uploadForm">
                          <input type="file" name="image" id="file" />
                      </div>
                      <img name="image_prev" src="{{url('upload',$product->image)}}" alt="" >
                      <div class="form-group">
                          <label for="productStatus">Show</label>
                          <input type="checkbox" name="status" id="productStatus" checked >
                      </div>
                      <div class="form-group">
                          <input type="submit" value="Update" class="btn btn-success float-right">
                      </div>
                  </form>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          {{-- col-6 --}}
      </section>

</div>
@endsection

resources/views/admin/orders/index.blade.php
@extends('admin.layouts.master')

@section('content')
<div class="content-wrapper">



    <section class="p-3">
            <div class="d-flex justify-content-end" style="width:100%">
                <div style="width:120px;margin-right:20px">
                    <select name="" id=""  class="btn btn-success"  style="width:100%;height:100%">
                        <option value="1">All data</option>
                        <option value="1">1</option>
                        <option value="1">1</option>

                    </select>
                </div>
                <div class="d-flex">
                        <input type="text" value="" placeholder="Search Email or Id" style="width:200px">
                        <button>Search</button>
                </div>
            </div>
    </section>
    <section>
        <div class="d-flex justify-content-between">
            <div style="margin-left:10px;display:flex;flex-direction: row;align-items: center">
                <div><input type="checkbox" name="checkAll" id="checkorder-all"></div>
                <div style="margin-left:20px"><Button class="btn btn-danger" id="deleteorder-checked">Delete</Button></div>
                <div style="margin-left:20px"><button class="btn btn-success">Refresh</button></div>
                <div style="margin-left:20px"><button>ID Desc</button></div>
                <div style="margin-left:20px"><button>Sort</button></div>
            </div>
            <div style="margin-right:20px">
                <a href="{{route('order.create')}}" class="btn btn-success">Add new</a>
            </div>
        </div>
    </section>

    <!-- /.box-header -->
    <section id="pjax-container" class="table-list">
    <div class="box-body table-responsive no-padding" >
        <table class="table table-hover">
        <thead>
           <tr>
               <th></th>
               <th>STT</th>
               <th>User</th>
               <th>Subprice</th>
               <th>Shipping</th>
               <th>Discount</th>
               <th>Total</th>
               <th>PM Method</th>
               <th>Status</th>
               <th>Actions</th>
           </tr>
        </thead>
        <tbody>
            @foreach ($orders as $key =>$order)
            <tr>
                <td><input value="{{$order->id}}" type="checkbox" name="order" id="order-{{$order->id}}"></td>
                <td>{{$key}}</td>
                <td>{{$order->user->email}}</td>
                <td>${{$order->subtotal+$order->discount}}</td>
                <td>{{$order->shipping}}</td>
                <td>{{$order->discount}}</td>
                <td>${{($order->subtotal + $order->shipping)}}</td>
                <td>{{$order->payment_method}}</td>
                <td>{{$order->status ==1?"show":"hide"}}</td>
                <td>
                        <a href="{{route('order.show',$order->id)}}"><span title="Edit" type="button" class="btn btn-flat btn-primary"><i class="far fa-eye"></i></span></a>&nbsp;
                        <button  data-id="{{$order->id}}" title="Delete" class="btn btn-flat btn-danger deleteorder"><i class="fa fa-trash"></i></button></td>
                </td>
            </tr>

            @endforeach

        </tbody>
        </table>
    </div>
    <div style="display:flex;align-self: center;justify-content: center">
        {{$orders->links()}}
    </div>
    </section>
    <!-- /.box-body -->
    </div>

</div>


@endsection

resources/views/admin/orders/show.blade.php
@extends('admin.layouts.master')

@section('content')
<script src="{{asset('admin/plugins/jquery/jquery.min.js')}}"></script>

<div class="content-wrapper">
    <section class="content">
        <div class="row">
          <div class="col-md-6">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Customer Information</h3>
                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i></button>
                </div>
              </div>
              <div class="card-body">
                <div class="form-group dropdown-customer">
                  <label for="inputQueryCustomer">Enter Customer</label>
                  <input disabled type="text" value="{{$order->user->name}}" id="inputQueryCustomer" class="form-control dropdown-btn-customer customer-name">
                  <div class="dropdown-content-customer" id="show-query-customer">
                    {{--  --}}

                  </div>
                </div>
                <div class="form-group">
                    <label for="inputEmail">Email</label>
                    <input disabled type="text" value="{{$order->user->email}}" id="inputEmail" class="form-control customer-email">
                </div>
                <div class="form-group">
                    <label for="inputPhone">Phone</label>
                    <input disabled type="text" value="{{$order->user->phone}}" id="inputPhone" class="form-control customer-phone">
                </div>
                <div class="form-group">
                    <label for="inputAddress">Address</label>
                    <input disabled type="text" value="{{$order->user->address}}" id="inputAddress" class="form-control customer-address">
                </div>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

          </div>

          <div class="col-md-6">
            <div class="card card-secondary">
              <div class="card-header">
                <h3 class="card-title">Product Information</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i></button>
                </div>
              </div>
              <div class="card-body">
                <div class="btn btn-success totalPrice-wrapper">
                    <span>Total Price: </span> <span id="show-totalPrice">{{$order->subtotal}}</span>
                </div>
                <div class="list-group" id="show-product-added">
                    @foreach ($order->orderDetail as $order)
                    <div class="card card-added-product" data-id='+e.id+' >
                        <h5 class="card-header">{{$order->product->name}}</h5>
                        <div class="card-body" style="display:flex;flex-direction:row">
                            <div class='card-text'><img width='100px' src='{{ url('default.jpg') }}' /></div>
                            <div><label>Quantity:</label> <span>{{$order->quantity}}</span></div>
                        </div>
                    </div>
                    @endforeach

                </div>


                {{-- Product show here --}}
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>


        <div class="row">

        </div>




        {{--  --}}
      </section>

</div>

<script>

</script>

<style>
    .productWrapper{
        display: flex;
        flex-direction: row;
        flex-wrap:wrap;
        margin-top: 10px;
        justify-content: space-between;
        align-items: center

    }
    .productWrapper:hover{
        background-color: azure;
        cursor: pointer;
    }
    .product-name{
        padding: 20px;
    }
    .btn-add a{
        color:white
    }
    .dropbtn {
        background-color: #4CAF50;
        color: white;
        padding: 16px;
        font-size: 16px;
        border: none;

    }

      .dropdown {
        position: relative;
        display: inline-block;
        width: 100%;
      }

      .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f1f1f1;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
        width: 100%;
      }

      .dropdown-content a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
      }

      .dropdown-content a:hover {background-color: #ddd;}

      .dropdown:hover .dropdown-content {display: block;}

      .dropdown:hover .dropbtn {background-color: #3e8e41;}

      {{-- customer query --}}
      .dropbtn-customer {
        background-color: #4CAF50;
        color: white;
        padding: 16px;
        font-size: 16px;
        border: none;

    }

      .dropdown-customer {
        position: relative;
        display: inline-block;
        width: 100%;
      }

      .dropdown-content-customer {
        display: none;
        position: absolute;
        background-color: #f1f1f1;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
        width: 100%;
      }

      .dropdown-content-customer a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
      }

      .dropdown-content-customer a:hover {background-color: #ddd;}

      .dropdown-customer:hover .dropdown-content-customer {display: block;}

      .dropdown-customer:hover .dropbtn-customer {background-color: #3e8e41;}
      .customer-query-card{
          display: flex;
          align-items: center;

      }
      .customer-query-text{
          padding-left: 20px;
      }
      .customer-query-card:hover{
          background-color: aliceblue;
          cursor: pointer;
      }
      #show-totalPrice{
        font-weight: bold;
        color: cornsilk;
      }
      .totalPrice-wrapper{
        display: flex;
        justify-content: center;
      }
</style>
@endsection